--reports

SELECT * FROM reports;

insert into reports(name, title, DESCRIPTION, SQL_CODE, REPORT_TYPE, PARENT_REPORT_ID)
select 'report ' || to_char(rownum), 'Report ' || to_char(rownum),'Report Desc' || to_char(rownum),'SELECT * FROM payments', 1, 1
from dual
connect by level <= 100;

SELECT * FROM reports WHERE report_type = 1 OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

--payments

SELECT * from PAYMENTS;

DROP TABLE payments;

SELECT COUNT (*) FROM payments

CREATE TABLE payments(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  description VARCHAR(50) NOT NULL,
  txdate DATE,
  country VARCHAR(50) NOT NULL,
  create_date TIMESTAMP(0),
  amount NUMBER
);

insert into payments(description, txdate, country, amount, create_date)
select 'payment desc ' || to_char(rownum), sysdate, 'Georgia', 100, LOCALTIMESTAMP(0)
from dual
connect by level <= 100;

--report parameters

SELECT * from report_params

DROP TABLE REPORT_PARAMS;

CREATE TABLE report_params (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  report_id NUMBER,
  param_type VARCHAR(50) NOT NULL, --type 'range', 'combo', 'date', 'text', 'number'
  param_code VARCHAR(50) NOT NULL,
  param_name VARCHAR(50) NOT NULL,
  combo_sql VARCHAR(1000)
);

INSERT INTO report_params (report_id, param_type, param_code, param_name, combo_sql) VALUES ('1', 'text', 'descr', 'descr', '0')


